default_agent: manager_worker
agents:
  manager_worker:
    name: manager_worker
    language: python
    node_version: '20'
    entrypoint: /Users/ioijoi/ghq/github.com/myuon/manager/src/manager/runtime.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/ioijoi/ghq/github.com/myuon/manager
    aws:
      execution_role: arn:aws:iam::941528793676:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-0046896a78
      execution_role_auto_create: false
      account: '941528793676'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-941528793676-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: manager_worker-68YWvn8UDE
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:941528793676:runtime/manager_worker-68YWvn8UDE
      agent_session_id: 60a01d5f-47ab-4b98-994e-04c6b046d440
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: manager_worker_mem-w8Nd8060wE
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:941528793676:memory/manager_worker_mem-w8Nd8060wE
      memory_name: manager_worker_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
